CREATE DATABASE IF NOT EXISTS prode_db;
USE prode_db;

CREATE TABLE usuarios(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VERCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE partidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  equipo_local VARCHAR(100) NOT NULL,
  equipo_visitante VARCHAR(100) NOT NULL,
  fecha DATETIME NOT NULL,
